package main

//go:generate go run .

import (
	"encoding/json"
	"fmt"
	"log"
	"net/url"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strings"

	"github.com/bep/godartsass/v2"
	"github.com/xeipuuv/gojsonschema"
	"github.com/zodimo/go-gen-m3/pkg/m3tokens"
)

const (
	themeJSONPath     = "m3/material-theme.json"
	localComponentDir = "m3web/v2.4.1/tokens"
	outputDir         = "theme"
	outputFile        = "theme/tokens.go"
)

var (
	targets = []string{
		"light", "dark",
		"light-medium-contrast", "light-high-contrast",
		"dark-medium-contrast", "dark-high-contrast",
	}
	components = []string{"filled-button", "elevated-card", "switch", "filled-text-field"}
	baselineStructuralTokens = map[string]string{
		"md.sys.shape.corner.full":   "999px",
		"md.sys.shape.corner.large":  "16px",
		"md.sys.shape.corner.medium": "12px",
		"md.sys.shape.corner.small":  "8px",
		"md.sys.shape.corner.none":   "0px",
	}

	cssPropRegex     = regexp.MustCompile(`([^:\s]+)\s*:\s*([^;\n]+);`)
	aliasRegex       = regexp.MustCompile(`\{([^}]+)\}`)
	varFallbackRegex = regexp.MustCompile(`var\(--md-[^,)]+,\s*([^)]+)\)`)
)

func main() {
	if _, err := os.Stat(themeJSONPath); os.IsNotExist(err) {
		log.Fatalf("Could not find theme file at: %s", themeJSONPath)
	}

	data, err := os.ReadFile(themeJSONPath)
	if err != nil {
		log.Fatal(err)
	}

	var themeData struct {
		Schemes map[string]map[string]string `json:"schemes"`
	}
	if err := json.Unmarshal(data, &themeData); err != nil {
		log.Fatal(err)
	}

	transpiler, err := godartsass.Start(godartsass.Options{})
	if err != nil {
		log.Fatal(err)
	}

	log.Println("Extracting token schema from SCSS...")
	schema, err := m3tokens.BuildSchema(transpiler, localComponentDir)
	if err != nil {
		log.Fatalf("Failed to extract schema: %v", err)
	}

	schemaJSON, err := json.MarshalIndent(schema, "", "  ")
	if err != nil {
		log.Fatalf("Failed to serialize schema: %v", err)
	}
	schemaPath := "pkg/m3tokens/schema.json"
	if err := os.WriteFile(schemaPath, schemaJSON, 0644); err != nil {
		log.Fatalf("Failed to write schema: %v", err)
	}

	absSchemaDefPath, _ := filepath.Abs("pkg/m3tokens/schema-def.json")
	schemaLoader := gojsonschema.NewReferenceLoader("file://" + absSchemaDefPath)
	documentLoader := gojsonschema.NewStringLoader(string(schemaJSON))
	result, err := gojsonschema.Validate(schemaLoader, documentLoader)
	if err != nil {
		log.Fatalf("Schema validation error: %v", err)
	}
	if !result.Valid() {
		for _, desc := range result.Errors() {
			log.Printf("- %s\n", desc)
		}
		log.Fatal("Extracted schema does not match schema-def.json")
	}
	log.Println("Schema extracted and validated successfully!")

	log.Println("Generating typed token system...")
	if err := m3tokens.Generate(schema, "pkg/m3tokens"); err != nil {
		log.Fatalf("Code generation failed: %v", err)
	}
	log.Println("Typed token system generated successfully!")


	absDir, err := filepath.Abs(localComponentDir)
	if err != nil {
		log.Fatal(err)
	}

	var goCode strings.Builder
	goCode.WriteString("package theme\n\n")
	goCode.WriteString("// Code generated by M3 Sync Pipeline via Modern Sass Engine. DO NOT EDIT.\n\n")

	for _, targetMode := range targets {
		log.Printf("Processing theme mode: [%s]", targetMode)

		allTokens := make(map[string]string, len(baselineStructuralTokens))
		for k, v := range baselineStructuralTokens {
			allTokens[k] = v
		}

		schemeColors, ok := themeData.Schemes[targetMode]
		if !ok {
			continue
		}

		for colorKey, hexVal := range schemeColors {
			kebabKey := camelToKebab(colorKey)
			allTokens[fmt.Sprintf("md.sys.color.%s", kebabKey)] = hexVal
		}

		customColorsSass := buildSassColorMap(schemeColors)

		for _, comp := range components {
			filename := fmt.Sprintf("_md-comp-%s.scss", comp)
			localFilePath := filepath.Join(localComponentDir, filename)

			if _, err := os.Stat(localFilePath); os.IsNotExist(err) {
				continue
			}

			absFilePath, err := filepath.Abs(localFilePath)
			if err != nil {
				log.Printf("Error resolving path for %s: %v", filename, err)
				continue
			}

			fileUrl := (&url.URL{Scheme: "file", Path: absFilePath}).String()

			sassBridgeCode := fmt.Sprintf(`
@use 'sass:map';
@use '%s' as compModule;
@use 'md-sys-elevation' as sysElevation;
@use 'md-sys-shape' as sysShape;
@use 'md-sys-state' as sysState;
@use 'md-sys-typescale' as sysTypescale;

$customColors: (
%s
);

$customDeps: (
  'md-sys-color': $customColors,
  'md-sys-elevation': sysElevation.values(),
  'md-sys-shape': sysShape.values($exclude-custom-properties: true),
  'md-sys-state': sysState.values(),
  'md-sys-typescale': sysTypescale.values($exclude-custom-properties: true),
);

$tokens: compModule.values($deps: $customDeps, $exclude-custom-properties: true);

.token-dump-%s {
  @each $key, $value in $tokens {
    --#{$key}: #{$value};
  }
}
`, fileUrl, customColorsSass, comp)

			res, err := transpiler.Execute(godartsass.Args{
				Source:       sassBridgeCode,
				URL:          (&url.URL{Scheme: "file", Path: filepath.Join(absDir, "gen.css.scss")}).String(),
				IncludePaths: []string{absDir},
			})
			if err != nil {
				log.Printf("Sass runtime exception for %s: %v", filename, err)
				continue
			}

			matches := cssPropRegex.FindAllStringSubmatch(res.CSS, -1)

			for _, match := range matches {
				property := strings.TrimPrefix(strings.TrimSpace(match[1]), "--")
				value := strings.TrimSpace(match[2])
				value = varFallbackRegex.ReplaceAllString(value, "$1")

				if strings.Contains(value, "$") || strings.Contains(value, "values-light") {
					continue
				}

				tokenKey := normalize(fmt.Sprintf("md.comp.%s.%s", comp, property))
				allTokens[tokenKey] = normalize(value)
			}
		}

		resolvedTokens := resolveAliases(allTokens)

		funcName := toPascalCase(targetMode)
		goCode.WriteString(fmt.Sprintf("// GetM3%sTokens returns the unrolled token definitions for \"%s\" using official keys\n", funcName, targetMode))
		goCode.WriteString(fmt.Sprintf("func GetM3%sTokens() map[string]string {\n\treturn map[string]string{\n", funcName))

		keys := make([]string, 0, len(resolvedTokens))
		for k := range resolvedTokens {
			keys = append(keys, k)
		}
		sort.Strings(keys)

		for _, k := range keys {
			goCode.WriteString(fmt.Sprintf("\t\t\"%s\": \"%s\",\n", k, resolvedTokens[k]))
		}

		goCode.WriteString("\t}\n}\n\n")
	}

	if err := os.MkdirAll(outputDir, 0755); err != nil {
		log.Fatal(err)
	}

	if err := os.WriteFile(outputFile, []byte(goCode.String()), 0644); err != nil {
		log.Fatal(err)
	}

	log.Println("Go maps utilizing official M3 token naming conventions written to ./theme/tokens.go!")
}

func camelToKebab(s string) string {
	var b strings.Builder
	for i, r := range s {
		if i > 0 && r >= 'A' && r <= 'Z' {
			b.WriteByte('-')
		}
		b.WriteRune(r)
	}
	return strings.ToLower(b.String())
}

func toPascalCase(s string) string {
	parts := strings.Split(s, "-")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func normalize(s string) string {
	s = strings.ReplaceAll(s, "-", ".")
	s = strings.ReplaceAll(s, "_", ".")
	return s
}

func buildSassColorMap(schemeColors map[string]string) string {
	var b strings.Builder
	keys := make([]string, 0, len(schemeColors))
	for k := range schemeColors {
		keys = append(keys, k)
	}
	sort.Strings(keys)

	for i, k := range keys {
		v := schemeColors[k]
		kebabKey := camelToKebab(k)
		if i > 0 {
			b.WriteString(",\n")
		}
		b.WriteString(fmt.Sprintf("  '%s': %s", kebabKey, v))
	}
	return b.String()
}

func resolveAliases(allTokens map[string]string) map[string]string {
	resolved := make(map[string]string, len(allTokens))

	for key, value := range allTokens {
		resolvedValue := value
		if aliasRegex.MatchString(value) {
			resolvedValue = aliasRegex.ReplaceAllStringFunc(value, func(match string) string {
				tokenPath := match[1 : len(match)-1]
				normalizedPath := normalize(tokenPath)
				if v, ok := allTokens[normalizedPath]; ok {
					return v
				}
				if v, ok := allTokens["md."+normalizedPath]; ok {
					return v
				}
				return match
			})
		}
		resolvedValue = strings.ReplaceAll(strings.ReplaceAll(resolvedValue, "{", ""), "}", "")
		officialM3Key := normalize(key)
		resolved[officialM3Key] = resolvedValue
	}

	return resolved
}
