package generator

import (
	"bytes"
	"fmt"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

func Generate(schema *Schema, outDir string) error {
	if err := os.MkdirAll(outDir, 0755); err != nil {
		return err
	}

	if err := generateEnums(schema, filepath.Join(outDir, "component_enums.go")); err != nil {
		return err
	}

	if err := generateStructs(schema, filepath.Join(outDir, "structs.go")); err != nil {
		return err
	}

	if err := generateSysMaps(schema, filepath.Join(outDir, "sys_maps.go")); err != nil {
		return err
	}

	if err := generateResolver(schema, filepath.Join(outDir, "resolver.go")); err != nil {
		return err
	}

	if err := generateTheme(schema, filepath.Join(outDir, "theme.go")); err != nil {
		return err
	}

	if err := generateFlatMap(schema, filepath.Join(outDir, "flat_map.go")); err != nil {
		return err
	}

	return nil
}

func toCamelCase(s string) string {
	parts := strings.Split(s, "-")
	for i := range parts {
		if len(parts[i]) > 0 {
			parts[i] = strings.ToUpper(parts[i][:1]) + parts[i][1:]
		}
	}
	return strings.Join(parts, "")
}

func generateEnums(schema *Schema, outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by m3-token-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package m3tokens\n\n")

	// Component Enum
	buf.WriteString("// Component Enum\n")
	buf.WriteString("type Component string\n\n")
	buf.WriteString("const (\n")
	for _, comp := range schema.Components {
		buf.WriteString(fmt.Sprintf("\tComponent%s Component = \"%s\"\n", toCamelCase(comp.Name), comp.Name))
	}
	buf.WriteString(")\n\n")

	buf.WriteString("func (c Component) String() string {\n\treturn string(c)\n}\n\n")

	// Collect unique categories, properties, and states
	categories := make(map[string]bool)
	properties := make(map[string]bool)
	states := make(map[string]bool)

	// Add standard states first
	standardStates := []string{"default", "hover", "focus", "pressed", "disabled", "dragged", "selected", "error", "active"}
	for _, st := range standardStates {
		states[st] = true
	}

	for _, comp := range schema.Components {
		for _, tok := range comp.SupportedTokens {
			if !hasStatePrefix(tok) {
				cat, prop := parseTokenCatProp(tok)
				categories[cat] = true
				properties[prop] = true
			}
		}
		for _, statePrefix := range comp.StatePrefixes {
			state := strings.TrimSuffix(statePrefix, "-")
			states[state] = true
		}
	}

	// TokenCategory Enum
	catKeys := make([]string, 0, len(categories))
	for k := range categories {
		catKeys = append(catKeys, k)
	}
	sort.Strings(catKeys)
	buf.WriteString("// TokenCategory Enum\n")
	buf.WriteString("const (\n")
	for _, cat := range catKeys {
		buf.WriteString(fmt.Sprintf("\tCategory%s TokenCategory = \"%s\"\n", toCamelCase(cat), cat))
	}
	buf.WriteString(")\n\n")

	// TokenProperty Enum
	propKeys := make([]string, 0, len(properties))
	for k := range properties {
		propKeys = append(propKeys, k)
	}
	sort.Strings(propKeys)
	buf.WriteString("// TokenProperty Enum\n")
	buf.WriteString("const (\n")
	for _, prop := range propKeys {
		buf.WriteString(fmt.Sprintf("\tProperty%s TokenProperty = \"%s\"\n", toCamelCase(prop), prop))
	}
	buf.WriteString(")\n\n")

	// TokenState Enum (Bitmask)
	stateKeys := make([]string, 0, len(states))
	for k := range states {
		if k != "default" {
			stateKeys = append(stateKeys, k)
		}
	}
	sort.Strings(stateKeys)
	// Make sure standard states are somewhat ordered if needed, but alphabetical is fine for bitmask
	buf.WriteString("// TokenState Enum\n")
	buf.WriteString("const (\n")
	buf.WriteString("\tStateDefault TokenState = 0\n")
	for i, state := range stateKeys {
		buf.WriteString(fmt.Sprintf("\tState%s TokenState = 1 << %d\n", toCamelCase(state), i))
	}
	buf.WriteString(")\n\n")

	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

func generateStructs(schema *Schema, outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by m3-token-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package m3tokens\n\n")

	for _, comp := range schema.Components {
		structName := toCamelCase(comp.Name) + "Tokens"
		buf.WriteString(fmt.Sprintf("type %s struct {\n", structName))

		// Sort state prefixes by length descending
		prefixes := make([]string, len(comp.StatePrefixes))
		copy(prefixes, comp.StatePrefixes)
		sort.Slice(prefixes, func(i, j int) bool {
			return len(prefixes[i]) > len(prefixes[j])
		})

		// Parse base tokens into categories
		compCats := make(map[string]map[string]bool)
		for _, tok := range comp.SupportedTokens {
			baseTok := tok
			if hasStatePrefix(tok) {
				for _, statePrefix := range prefixes {
					if strings.HasPrefix(tok, statePrefix) {
						baseTok = strings.TrimPrefix(tok, statePrefix)
						break
					}
				}
			}
			cat, prop := parseTokenCatProp(baseTok)
			if compCats[cat] == nil {
				compCats[cat] = make(map[string]bool)
			}
			compCats[cat][prop] = true
		}

		cats := make([]string, 0, len(compCats))
		for cat := range compCats {
			cats = append(cats, cat)
		}
		sort.Strings(cats)

		for _, cat := range cats {
			catName := toCamelCase(cat)
			// Generate inline anonymous struct for category
			buf.WriteString(fmt.Sprintf("\t%s struct {\n", catName))

			props := make([]string, 0, len(compCats[cat]))
			for prop := range compCats[cat] {
				props = append(props, prop)
			}
			sort.Strings(props)
			for _, prop := range props {
				tokenName := cat
				if prop != "value" {
					tokenName = cat + "-" + prop
				}
				buf.WriteString(fmt.Sprintf("\t\t%s string `m3:\"%s\"`\n", toCamelCase(prop), tokenName))
			}
			buf.WriteString("\t}\n")
		}

		for _, statePrefix := range comp.StatePrefixes {
			state := strings.TrimSuffix(statePrefix, "-")
			overlayName := toCamelCase(comp.Name) + toCamelCase(state) + "Overlay"
			buf.WriteString(fmt.Sprintf("\t%s *%s\n", toCamelCase(state), overlayName))
		}

		buf.WriteString("}\n\n")

		for _, statePrefix := range comp.StatePrefixes {
			state := strings.TrimSuffix(statePrefix, "-")
			overlayName := toCamelCase(comp.Name) + toCamelCase(state) + "Overlay"
			buf.WriteString(fmt.Sprintf("type %s struct {\n", overlayName))

			propsMap := make(map[string]string)
			for _, tok := range comp.SupportedTokens {
				var matchedPrefix string
				for _, p := range prefixes {
					if strings.HasPrefix(tok, p) {
						matchedPrefix = p
						break
					}
				}
				if matchedPrefix == statePrefix {
					baseTok := strings.TrimPrefix(tok, statePrefix)
					cat, p := parseTokenCatProp(baseTok)
					propsMap[toCamelCase(cat)+toCamelCase(p)] = baseTok
				}
			}
			props := make([]string, 0, len(propsMap))
			for prop := range propsMap {
				props = append(props, prop)
			}
			sort.Strings(props)
			for _, prop := range props {
				buf.WriteString(fmt.Sprintf("\t%s *string `m3:\"%s\"`\n", prop, statePrefix+propsMap[prop]))
			}
			buf.WriteString("}\n\n")
		}
	}

	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

func hasStatePrefix(token string) bool {
	stateVocab := []string{"hover-", "focus-", "pressed-", "disabled-", "dragged-", "selected-", "error-", "active-", "toggle-"}
	for _, state := range stateVocab {
		if strings.HasPrefix(token, state) {
			return true
		}
	}
	return false
}

func parseTokenCatProp(token string) (string, string) {
	knownCategories := []string{
		"container", "icon", "label-text", "state-layer", "outline",
		"active-indicator", "supporting-text", "leading-content",
		"trailing-content", "headline", "content", "leading-icon",
		"trailing-icon", "four-color", "bottom", "top", "with-label", "with-leading-icon",
		"with-trailing-icon", "with-leading-content", "with-trailing-content",
		"primary", "secondary", "tertiary", "small", "large", "lowered", "toggle-selected",
		"toggle", "unselected", "action",
	}

	for _, cat := range knownCategories {
		if strings.HasPrefix(token, cat) {
			if len(token) == len(cat) {
				return cat, "value"
			}
			if token[len(cat)] == '-' {
				return cat, token[len(cat)+1:]
			}
		}
	}

	parts := strings.SplitN(token, "-", 2)
	if len(parts) == 1 {
		return parts[0], "value"
	}
	return parts[0], parts[1]
}

func generateSysMaps(schema *Schema, outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by m3-token-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package m3tokens\n\n")

	var sysNames []string
	for name := range schema.SystemModules {
		sysNames = append(sysNames, name)
	}
	sort.Strings(sysNames)

	for _, name := range sysNames {
		m := schema.SystemModules[name]
		mapName := toCamelCase(name)
		buf.WriteString(fmt.Sprintf("var %s = map[string]string{\n", mapName))
		keys := make([]string, 0, len(m))
		for k := range m {
			keys = append(keys, k)
		}
		sort.Strings(keys)
		for _, k := range keys {
			buf.WriteString(fmt.Sprintf("\t\"%s\": \"%s\",\n", k, m[k]))
		}
		buf.WriteString("}\n\n")
	}

	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

func generateResolver(schema *Schema, outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by m3-token-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package m3tokens\n\n")

	buf.WriteString("type Resolver struct {\n")
	buf.WriteString("\ttheme *Theme\n")
	buf.WriteString("}\n\n")

	for _, comp := range schema.Components {
		compName := toCamelCase(comp.Name)
		buf.WriteString(fmt.Sprintf("func (r *Resolver) %s() *%sResolver {\n", compName, compName))
		buf.WriteString(fmt.Sprintf("\treturn &%sResolver{tokens: r.theme.%sTokens}\n", compName, compName))
		buf.WriteString("}\n\n")

		buf.WriteString(fmt.Sprintf("type %sResolver struct {\n", compName))
		buf.WriteString(fmt.Sprintf("\ttokens *%sTokens\n", compName))
		buf.WriteString("}\n\n")

		// Sort state prefixes by length descending for priority (compound first)
		prefixes := make([]string, len(comp.StatePrefixes))
		copy(prefixes, comp.StatePrefixes)
		sort.Slice(prefixes, func(i, j int) bool {
			return len(prefixes[i]) > len(prefixes[j])
		})

		uniqueBaseTokens := make(map[string]bool)
		for _, tok := range comp.SupportedTokens {
			if hasStatePrefix(tok) {
				for _, statePrefix := range prefixes {
					if strings.HasPrefix(tok, statePrefix) {
						uniqueBaseTokens[strings.TrimPrefix(tok, statePrefix)] = true
						break
					}
				}
			} else {
				uniqueBaseTokens[tok] = true
			}
		}

		baseTokens := make([]string, 0, len(uniqueBaseTokens))
		for tok := range uniqueBaseTokens {
			baseTokens = append(baseTokens, tok)
		}
		sort.Strings(baseTokens)

		for _, baseTok := range baseTokens {
			cat, prop := parseTokenCatProp(baseTok)
			methodName := toCamelCase(cat) + toCamelCase(prop)

			buf.WriteString(fmt.Sprintf("func (r *%sResolver) %s(state TokenState) string {\n", compName, methodName))

			for _, statePrefix := range prefixes {
				stateName := toCamelCase(strings.TrimSuffix(statePrefix, "-"))

				hasProp := false
				for _, t := range comp.SupportedTokens {
					if t == statePrefix+baseTok {
						var matchedPrefix string
						for _, p := range prefixes {
							if strings.HasPrefix(t, p) {
								matchedPrefix = p
								break
							}
						}
						if matchedPrefix == statePrefix {
							hasProp = true
						}
						break
					}
				}

				if hasProp {
					// Generate bitwise check for this prefix
					parts := strings.Split(strings.TrimSuffix(statePrefix, "-"), "-")
					var stateChecks []string
					for _, p := range parts {
						if p != "" {
							stateChecks = append(stateChecks, fmt.Sprintf("State%s", toCamelCase(p)))
						}
					}

					if len(stateChecks) > 0 {
						mask := strings.Join(stateChecks, " | ")
						buf.WriteString(fmt.Sprintf("\tif state & (%s) == (%s) {\n", mask, mask))
						buf.WriteString(fmt.Sprintf("\t\tif r.tokens.%s != nil && r.tokens.%s.%s != nil {\n", stateName, stateName, methodName))
						buf.WriteString(fmt.Sprintf("\t\t\treturn *r.tokens.%s.%s\n", stateName, methodName))
						buf.WriteString("\t\t}\n")
						buf.WriteString("\t}\n")
					}
				}
			}

			buf.WriteString(fmt.Sprintf("\treturn r.tokens.%s.%s\n", toCamelCase(cat), toCamelCase(prop)))
			buf.WriteString("}\n\n")
		}
	}

	buf.WriteString("func (r *Resolver) Custom(name string, token string, state TokenState) string {\n")
	buf.WriteString("\ttokens, ok := r.theme.CustomComponents[name]\n")
	buf.WriteString("\tif !ok { return \"\" }\n")
	buf.WriteString("\t// Basic state resolution for custom components\n")
	buf.WriteString("\t// Checks compound overlays then single overlays based on state bitmask\n")
	buf.WriteString("\tif state != StateDefault {\n")
	buf.WriteString("\t\t// This is a simplified check for custom components. For full compound support,\n")
	buf.WriteString("\t\t// developers should rely on typed components or explicit token names.\n")
	buf.WriteString("\t\tstates := []struct{ s TokenState; p string }{\n")
	buf.WriteString("\t\t\t{StateSelected | StateHover, \"selected-hover-\"},\n")
	buf.WriteString("\t\t\t{StateSelected | StateFocus, \"selected-focus-\"},\n")
	buf.WriteString("\t\t\t{StateSelected | StatePressed, \"selected-pressed-\"},\n")
	buf.WriteString("\t\t\t{StateError | StateHover, \"error-hover-\"},\n")
	buf.WriteString("\t\t\t{StateError | StateFocus, \"error-focus-\"},\n")
	buf.WriteString("\t\t\t{StateDisabled, \"disabled-\"},\n")
	buf.WriteString("\t\t\t{StateError, \"error-\"},\n")
	buf.WriteString("\t\t\t{StatePressed, \"pressed-\"},\n")
	buf.WriteString("\t\t\t{StateFocus, \"focus-\"},\n")
	buf.WriteString("\t\t\t{StateHover, \"hover-\"},\n")
	buf.WriteString("\t\t\t{StateSelected, \"selected-\"},\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t\tfor _, st := range states {\n")
	buf.WriteString("\t\t\tif state & st.s == st.s {\n")
	buf.WriteString("\t\t\t\tif v, ok := tokens[st.p + token]; ok { return v }\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n")
	buf.WriteString("\treturn tokens[token]\n")
	buf.WriteString("}\n\n")

	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

func generateTheme(schema *Schema, outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by m3-token-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package m3tokens\n\n")

	buf.WriteString("type Theme struct {\n")
	buf.WriteString("\tResolver *Resolver\n")
	for _, comp := range schema.Components {
		compName := toCamelCase(comp.Name)
		buf.WriteString(fmt.Sprintf("\t%sTokens *%sTokens\n", compName, compName))
	}
	buf.WriteString("\tCustomComponents map[string]map[string]string\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func NewTheme(mode string) *Theme {\n")
	buf.WriteString("\ttheme := &Theme{}\n")
	buf.WriteString("\ttheme.Resolver = &Resolver{theme: theme}\n")
	buf.WriteString("\ttheme.CustomComponents = make(map[string]map[string]string)\n")
	buf.WriteString("\t// Initialize tokens based on mode (TODO: actually parse sys maps and populate)\n")
	for _, comp := range schema.Components {
		compName := toCamelCase(comp.Name)
		buf.WriteString(fmt.Sprintf("\ttheme.%sTokens = &%sTokens{}\n", compName, compName))
	}
	buf.WriteString("\treturn theme\n")
	buf.WriteString("}\n\n")

	buf.WriteString("func (t *Theme) RegisterCustomComponent(name string, tokens map[string]string) {\n")
	buf.WriteString("\tt.CustomComponents[name] = tokens\n")
	buf.WriteString("}\n\n")

	return os.WriteFile(outPath, buf.Bytes(), 0644)
}

func generateFlatMap(schema *Schema, outPath string) error {
	var buf bytes.Buffer
	buf.WriteString("// Code generated by m3-token-gen. DO NOT EDIT.\n\n")
	buf.WriteString("package m3tokens\n\n")
	buf.WriteString("import (\n\t\"fmt\"\n\t\"reflect\"\n\t\"strings\"\n)\n\n")

	buf.WriteString("func (t *Theme) FlatMap() map[string]string {\n")
	buf.WriteString("\tm := make(map[string]string)\n\n")

	buf.WriteString("\tvar extract func(string, reflect.Value)\n")
	buf.WriteString("\textract = func(prefix string, v reflect.Value) {\n")
	buf.WriteString("\t\tif v.Kind() == reflect.Ptr { v = v.Elem() }\n")
	buf.WriteString("\t\tif v.Kind() != reflect.Struct { return }\n")
	buf.WriteString("\t\tfor i := 0; i < v.NumField(); i++ {\n")
	buf.WriteString("\t\t\tf := v.Field(i)\n")
	buf.WriteString("\t\t\tt := v.Type().Field(i)\n")
	buf.WriteString("\t\t\ttag := t.Tag.Get(\"m3\")\n")
	buf.WriteString("\t\t\tif tag == \"\" {\n")
	buf.WriteString("\t\t\t\textract(prefix, f)\n")
	buf.WriteString("\t\t\t} else if f.Kind() == reflect.String && f.String() != \"\" {\n")
	buf.WriteString("\t\t\t\tm[fmt.Sprintf(\"md.comp.%s.%s\", prefix, strings.ReplaceAll(tag, \"-\", \".\"))] = f.String()\n")
	buf.WriteString("\t\t\t} else if f.Kind() == reflect.Ptr && !f.IsNil() && f.Elem().Kind() == reflect.String {\n")
	buf.WriteString("\t\t\t\tm[fmt.Sprintf(\"md.comp.%s.%s\", prefix, strings.ReplaceAll(tag, \"-\", \".\"))] = f.Elem().String()\n")
	buf.WriteString("\t\t\t}\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")

	for _, comp := range schema.Components {
		compName := toCamelCase(comp.Name)
		buf.WriteString(fmt.Sprintf("\textract(\"%s\", reflect.ValueOf(t.%sTokens))\n", strings.ReplaceAll(comp.Name, "-", "."), compName))
	}

	buf.WriteString("\tfor name, tokens := range t.CustomComponents {\n")
	buf.WriteString("\t\tfor k, v := range tokens {\n")
	buf.WriteString("\t\t\tm[fmt.Sprintf(\"md.comp.%s.%s\", strings.ReplaceAll(name, \"-\", \".\"), strings.ReplaceAll(k, \"-\", \".\"))] = v\n")
	buf.WriteString("\t\t}\n")
	buf.WriteString("\t}\n\n")

	buf.WriteString("\treturn m\n")
	buf.WriteString("}\n\n")

	return os.WriteFile(outPath, buf.Bytes(), 0644)
}
