import fs from 'fs';
import path from 'path';
import { pathToFileURL } from 'url';
import * as sass from 'sass';

const THEME_JSON_PATH = path.resolve('m3','material-theme.json');
const LOCAL_COMPONENT_DIR = path.resolve('m3web', 'v2.4.1', 'tokens');
const components = ['filled-button', 'elevated-card', 'switch', 'filled-text-field'];

// Non-color baseline tokens that are missing from the custom theme builder JSON export
const baselineStructuralTokens = {
  "md.sys.shape.corner.full": "999px",
  "md.sys.shape.corner.large": "16px",
  "md.sys.shape.corner.medium": "12px",
  "md.sys.shape.corner.small": "8px",
  "md.sys.shape.corner.none": "0px"
};

async function runPipeline() {
  // 1. Read and Parse your uploaded Figma Material Theme JSON
  if (!fs.existsSync(THEME_JSON_PATH)) {
    console.error(`❌ Could not find theme file at: ${THEME_JSON_PATH}`);
    return;
  }
  
  const themeData = JSON.parse(fs.readFileSync(THEME_JSON_PATH, 'utf8'));
  
  // We will generate an isolated token block for each theme mode variant found in your file
  const targets = ['light', 'dark', 'light-medium-contrast', 'light-high-contrast', 'dark-medium-contrast', 'dark-high-contrast'];
  
  let goCodeOutput = `package theme\n\n// Code generated by M3 Sync Pipeline via Modern Sass Engine. DO NOT EDIT.\n\n`;

  for (const targetMode of targets) {
    console.log(`\n🎨 Processing theme mode using official token keys: [${targetMode}]`);
    
    // Seed system variables
    const allTokens = { ...baselineStructuralTokens };
    
    const schemeColors = themeData.schemes[targetMode];
    if (!schemeColors) continue;
    
    // Ingest custom colors using official M3 structural naming
    for (const [colorKey, hexVal] of Object.entries(schemeColors)) {
      const kebabKey = colorKey.replace(/([A-Z])/g, '-$1').toLowerCase();
      allTokens[`md.sys.color.${kebabKey}`] = hexVal;
    }

    // Process and unroll local SCSS map code 
    for (const comp of components) {
      const filename = `_md-comp-${comp}.scss`;
      const localFilePath = path.join(LOCAL_COMPONENT_DIR, filename);
      
      if (!fs.existsSync(localFilePath)) continue;

      try {
        const fileUrl = pathToFileURL(localFilePath).href;
        const sassBridgeCode = `
          @use 'sass:meta';
          @use '${fileUrl}' as compModule;

          .token-dump-${comp} {
            @each $key, $value in meta.module-variables('compModule') {
              #{$key}: #{$value};
            }
          }
        `;

        const result = sass.compileString(sassBridgeCode, { loadPaths: [LOCAL_COMPONENT_DIR] });
        const cleanMatches = [...result.css.matchAll(/([^:\s]+)\s*:\s*([^;\n]+);/g)];

        cleanMatches.forEach(match => {
          const property = match[1].trim();
          let value = match[2].trim();

          // Transform platform-specific variables to standardized canonical design tokens
          value = value.replace(/var\(--md-sys-color-([^,)]+)[^)]*\)/g, '{md.sys.color.$1}');
          value = value.replace(/var\(--md-sys-shape-([^,)]+)[^)]*\)/g, '{md.sys.shape.$1}');
          value = value.replace(/var\(--md-sys-typescale-([^,)]+)[^)]*\)/g, '{md.sys.typescale.$1}');
          
          if (value.includes('(') || value.includes('$') || value.includes('values-light')) return;

          const tokenKey = `md.comp.${comp}.${property}`.replace(/[-_]/g, '.');
          allTokens[tokenKey] = value.replace(/[-_]/g, '.');
        });
      } catch (err) {
        console.error(`❌ Sass runtime exception for ${filename}:`, err.message);
      }
    }

    // Evaluate references across the tokens structure
    const resolvedTokens = {};
    for (const [key, value] of Object.entries(allTokens)) {
      let resolvedValue = value;
      const aliasRegex = /\{([^}]+)\}/g;
      
      if (aliasRegex.test(value)) {
        resolvedValue = value.replace(aliasRegex, (_, tokenPath) => {
          const normalizedPath = tokenPath.replace(/[-_]/g, '.');
          return allTokens[normalizedPath] || allTokens[`md.${normalizedPath}`] || value;
        });
      }

      resolvedValue = resolvedValue.replace(/[{}]/g, '');
      
      // Preserve standard M3 dotted naming path for the dictionary map key
      const officialM3Key = key.replace(/[-_]/g, '.');
      resolvedTokens[officialM3Key] = resolvedValue;
    }

    // Build the Go functional maps
    const camelModeName = targetMode.split('-').map((w, i) => i === 0 ? w : w.charAt(0).toUpperCase() + w.slice(1)).join('');
    const funcName = camelModeName.charAt(0).toUpperCase() + camelModeName.slice(1);
    
    goCodeOutput += `// GetM3${funcName}Tokens returns the unrolled token definitions for "${targetMode}" using official keys\n`;
    goCodeOutput += `func GetM3${funcName}Tokens() map[string]string {\n\treturn map[string]string{\n`;
    
    for (const [officialKey, resolvedVal] of Object.entries(resolvedTokens)) {
      goCodeOutput += `\t\t"${officialKey}": "${resolvedVal}",\n`;
    }
    goCodeOutput += `\t}\n}\n\n`;
  }

  if (!fs.existsSync('./theme')) fs.mkdirSync('./theme');
  fs.writeFileSync('./theme/tokens.go', goCodeOutput);
  console.log('🚀 Go maps utilizing official M3 token naming conventions written to ./theme/tokens.go!');
}

runPipeline();