// Code generated by m3-token-gen. DO NOT EDIT.

package m3tokens

import (
	"fmt"
	"reflect"
	"strings"
)

func (t *Theme) FlatMap() map[string]string {
	m := make(map[string]string)

	var extract func(string, reflect.Value)
	extract = func(prefix string, v reflect.Value) {
		if v.Kind() == reflect.Ptr {
			v = v.Elem()
		}
		if v.Kind() != reflect.Struct {
			return
		}
		for i := 0; i < v.NumField(); i++ {
			f := v.Field(i)
			t := v.Type().Field(i)
			tag := t.Tag.Get("m3")
			if tag == "" {
				extract(prefix, f)
			} else if f.Kind() == reflect.String && f.String() != "" {
				m[fmt.Sprintf("md.comp.%s.%s", prefix, strings.ReplaceAll(tag, "-", "."))] = f.String()
			} else if f.Kind() == reflect.Ptr && !f.IsNil() && f.Elem().Kind() == reflect.String {
				m[fmt.Sprintf("md.comp.%s.%s", prefix, strings.ReplaceAll(tag, "-", "."))] = f.Elem().String()
			}
		}
	}

	extract("assist.chip", reflect.ValueOf(t.AssistChipTokens))
	extract("checkbox", reflect.ValueOf(t.CheckboxTokens))
	extract("circular.progress", reflect.ValueOf(t.CircularProgressTokens))
	extract("dialog", reflect.ValueOf(t.DialogTokens))
	extract("divider", reflect.ValueOf(t.DividerTokens))
	extract("elevated.button", reflect.ValueOf(t.ElevatedButtonTokens))
	extract("elevated.card", reflect.ValueOf(t.ElevatedCardTokens))
	extract("elevation", reflect.ValueOf(t.ElevationTokens))
	extract("fab.branded", reflect.ValueOf(t.FabBrandedTokens))
	extract("fab", reflect.ValueOf(t.FabTokens))
	extract("filled.button", reflect.ValueOf(t.FilledButtonTokens))
	extract("filled.card", reflect.ValueOf(t.FilledCardTokens))
	extract("filled.field", reflect.ValueOf(t.FilledFieldTokens))
	extract("filled.icon.button", reflect.ValueOf(t.FilledIconButtonTokens))
	extract("filled.select", reflect.ValueOf(t.FilledSelectTokens))
	extract("filled.text.field", reflect.ValueOf(t.FilledTextFieldTokens))
	extract("filled.tonal.button", reflect.ValueOf(t.FilledTonalButtonTokens))
	extract("filled.tonal.icon.button", reflect.ValueOf(t.FilledTonalIconButtonTokens))
	extract("filter.chip", reflect.ValueOf(t.FilterChipTokens))
	extract("focus.ring", reflect.ValueOf(t.FocusRingTokens))
	extract("icon.button", reflect.ValueOf(t.IconButtonTokens))
	extract("icon", reflect.ValueOf(t.IconTokens))
	extract("input.chip", reflect.ValueOf(t.InputChipTokens))
	extract("item", reflect.ValueOf(t.ItemTokens))
	extract("linear.progress", reflect.ValueOf(t.LinearProgressTokens))
	extract("list.item", reflect.ValueOf(t.ListItemTokens))
	extract("list", reflect.ValueOf(t.ListTokens))
	extract("menu.item", reflect.ValueOf(t.MenuItemTokens))
	extract("menu", reflect.ValueOf(t.MenuTokens))
	extract("outlined.button", reflect.ValueOf(t.OutlinedButtonTokens))
	extract("outlined.card", reflect.ValueOf(t.OutlinedCardTokens))
	extract("outlined.field", reflect.ValueOf(t.OutlinedFieldTokens))
	extract("outlined.icon.button", reflect.ValueOf(t.OutlinedIconButtonTokens))
	extract("outlined.segmented.button", reflect.ValueOf(t.OutlinedSegmentedButtonTokens))
	extract("outlined.select", reflect.ValueOf(t.OutlinedSelectTokens))
	extract("outlined.text.field", reflect.ValueOf(t.OutlinedTextFieldTokens))
	extract("primary.tab", reflect.ValueOf(t.PrimaryTabTokens))
	extract("radio", reflect.ValueOf(t.RadioTokens))
	extract("ripple", reflect.ValueOf(t.RippleTokens))
	extract("secondary.tab", reflect.ValueOf(t.SecondaryTabTokens))
	extract("slider", reflect.ValueOf(t.SliderTokens))
	extract("suggestion.chip", reflect.ValueOf(t.SuggestionChipTokens))
	extract("switch", reflect.ValueOf(t.SwitchTokens))
	extract("text.button", reflect.ValueOf(t.TextButtonTokens))
	for name, tokens := range t.CustomComponents {
		for k, v := range tokens {
			m[fmt.Sprintf("md.comp.%s.%s", strings.ReplaceAll(name, "-", "."), strings.ReplaceAll(k, "-", "."))] = v
		}
	}

	return m
}
