// Code generated by m3-token-gen. DO NOT EDIT.

package m3tokens

type Theme struct {
	Resolver                      *Resolver
	AssistChipTokens              *AssistChipTokens
	CheckboxTokens                *CheckboxTokens
	CircularProgressTokens        *CircularProgressTokens
	DialogTokens                  *DialogTokens
	DividerTokens                 *DividerTokens
	ElevatedButtonTokens          *ElevatedButtonTokens
	ElevatedCardTokens            *ElevatedCardTokens
	ElevationTokens               *ElevationTokens
	FabBrandedTokens              *FabBrandedTokens
	FabTokens                     *FabTokens
	FilledButtonTokens            *FilledButtonTokens
	FilledCardTokens              *FilledCardTokens
	FilledFieldTokens             *FilledFieldTokens
	FilledIconButtonTokens        *FilledIconButtonTokens
	FilledSelectTokens            *FilledSelectTokens
	FilledTextFieldTokens         *FilledTextFieldTokens
	FilledTonalButtonTokens       *FilledTonalButtonTokens
	FilledTonalIconButtonTokens   *FilledTonalIconButtonTokens
	FilterChipTokens              *FilterChipTokens
	FocusRingTokens               *FocusRingTokens
	IconButtonTokens              *IconButtonTokens
	IconTokens                    *IconTokens
	InputChipTokens               *InputChipTokens
	ItemTokens                    *ItemTokens
	LinearProgressTokens          *LinearProgressTokens
	ListItemTokens                *ListItemTokens
	ListTokens                    *ListTokens
	MenuItemTokens                *MenuItemTokens
	MenuTokens                    *MenuTokens
	OutlinedButtonTokens          *OutlinedButtonTokens
	OutlinedCardTokens            *OutlinedCardTokens
	OutlinedFieldTokens           *OutlinedFieldTokens
	OutlinedIconButtonTokens      *OutlinedIconButtonTokens
	OutlinedSegmentedButtonTokens *OutlinedSegmentedButtonTokens
	OutlinedSelectTokens          *OutlinedSelectTokens
	OutlinedTextFieldTokens       *OutlinedTextFieldTokens
	PrimaryTabTokens              *PrimaryTabTokens
	RadioTokens                   *RadioTokens
	RippleTokens                  *RippleTokens
	SecondaryTabTokens            *SecondaryTabTokens
	SliderTokens                  *SliderTokens
	SuggestionChipTokens          *SuggestionChipTokens
	SwitchTokens                  *SwitchTokens
	TextButtonTokens              *TextButtonTokens
	CustomComponents              map[string]map[string]string
}

func NewTheme(mode string) *Theme {
	theme := &Theme{}
	theme.Resolver = &Resolver{theme: theme}
	theme.CustomComponents = make(map[string]map[string]string)
	// Initialize tokens based on mode (TODO: actually parse sys maps and populate)
	theme.AssistChipTokens = &AssistChipTokens{}
	theme.CheckboxTokens = &CheckboxTokens{}
	theme.CircularProgressTokens = &CircularProgressTokens{}
	theme.DialogTokens = &DialogTokens{}
	theme.DividerTokens = &DividerTokens{}
	theme.ElevatedButtonTokens = &ElevatedButtonTokens{}
	theme.ElevatedCardTokens = &ElevatedCardTokens{}
	theme.ElevationTokens = &ElevationTokens{}
	theme.FabBrandedTokens = &FabBrandedTokens{}
	theme.FabTokens = &FabTokens{}
	theme.FilledButtonTokens = &FilledButtonTokens{}
	theme.FilledCardTokens = &FilledCardTokens{}
	theme.FilledFieldTokens = &FilledFieldTokens{}
	theme.FilledIconButtonTokens = &FilledIconButtonTokens{}
	theme.FilledSelectTokens = &FilledSelectTokens{}
	theme.FilledTextFieldTokens = &FilledTextFieldTokens{}
	theme.FilledTonalButtonTokens = &FilledTonalButtonTokens{}
	theme.FilledTonalIconButtonTokens = &FilledTonalIconButtonTokens{}
	theme.FilterChipTokens = &FilterChipTokens{}
	theme.FocusRingTokens = &FocusRingTokens{}
	theme.IconButtonTokens = &IconButtonTokens{}
	theme.IconTokens = &IconTokens{}
	theme.InputChipTokens = &InputChipTokens{}
	theme.ItemTokens = &ItemTokens{}
	theme.LinearProgressTokens = &LinearProgressTokens{}
	theme.ListItemTokens = &ListItemTokens{}
	theme.ListTokens = &ListTokens{}
	theme.MenuItemTokens = &MenuItemTokens{}
	theme.MenuTokens = &MenuTokens{}
	theme.OutlinedButtonTokens = &OutlinedButtonTokens{}
	theme.OutlinedCardTokens = &OutlinedCardTokens{}
	theme.OutlinedFieldTokens = &OutlinedFieldTokens{}
	theme.OutlinedIconButtonTokens = &OutlinedIconButtonTokens{}
	theme.OutlinedSegmentedButtonTokens = &OutlinedSegmentedButtonTokens{}
	theme.OutlinedSelectTokens = &OutlinedSelectTokens{}
	theme.OutlinedTextFieldTokens = &OutlinedTextFieldTokens{}
	theme.PrimaryTabTokens = &PrimaryTabTokens{}
	theme.RadioTokens = &RadioTokens{}
	theme.RippleTokens = &RippleTokens{}
	theme.SecondaryTabTokens = &SecondaryTabTokens{}
	theme.SliderTokens = &SliderTokens{}
	theme.SuggestionChipTokens = &SuggestionChipTokens{}
	theme.SwitchTokens = &SwitchTokens{}
	theme.TextButtonTokens = &TextButtonTokens{}
	return theme
}

func (t *Theme) RegisterCustomComponent(name string, tokens map[string]string) {
	t.CustomComponents[name] = tokens
}
